# Generated by Django 5.0.3 on 2024-03-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_months', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserTimeline',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.student')),
                ('timeline', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.student')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('coins', models.PositiveIntegerField(default=0)),
                ('payment_id', models.CharField(default='nopay', max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
            ],
        ),
    ]
