# Generated by Django 5.0.3 on 2024-03-10 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('district', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('building_number', models.CharField(max_length=10)),
                ('college_name', models.CharField(max_length=100)),
                ('college_id', models.CharField(max_length=20)),
                ('route_details', models.TextField()),
                ('uid', models.CharField(blank=True, max_length=15, unique=True)),
                ('card_id', models.CharField(blank=True, max_length=15, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
